### ISSUE TITLE
Unknown Uncaught Exception

### ISSUE THREAD

**Issue by josve05a** [irccloud/irccloud-desktop#110]
Not sure if this is an error worth reporting, or what happened. All I know was that an error message appeared and said that an error had been logged.

```
[2018-02-05 19:02:01.316] [info] Checking for update
[2018-02-05 19:02:06.797] [info] Found version 0.6.0 (url: irccloud-desktop-0.6.0-mac.zip, IRCCloud-0.6.0.dmg)
[2018-02-05 19:02:06.799] [info] Downloading update from irccloud-desktop-0.6.0-mac.zip, IRCCloud-0.6.0.dmg
[2018-02-05 19:02:06.876] [info] / requested
[2018-02-05 19:02:06.886] [info] /app.zip requested
[2018-02-05 19:02:07.244] [info] download-progress listener count: 0
[2018-02-05 19:05:12.730] [warn] Error: Begäran nådde en maxtidsgräns.

[2018-02-05 19:05:12.733] [error] Error: Error: Begäran nådde en maxtidsgräns.
[2018-02-05 19:05:12.739] [error] Error: Error: Begäran nådde en maxtidsgräns.
    at /Applications/IRCCloud.app/Contents/Resources/app.asar/node_modules/electron-updater/src/MacUpdater.ts:44:12
From previous event:
    at MacUpdater.doDownloadUpdate (/Applications/IRCCloud.app/Contents/Resources/app.asar/node_modules/electron-updater/out/MacUpdater.js:127:11)
    at /Applications/IRCCloud.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:304:25
    at Generator.next (<anonymous>)
From previous event:
    at MacUpdater.downloadUpdate (/Applications/IRCCloud.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:355:11)
    at /Applications/IRCCloud.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:280:49
From previous event:
    at MacUpdater.doCheckForUpdates (/Applications/IRCCloud.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:326:11)
    at /Applications/IRCCloud.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:228:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at MacUpdater._checkForUpdates (/Applications/IRCCloud.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:280:11)
    at MacUpdater.checkForUpdates (/Applications/IRCCloud.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:177:35)
    at Object.setup (/Applications/IRCCloud.app/Contents/Resources/app.asar/app/auto_update.js:41:19)
    at App.<anonymous> (/Applications/IRCCloud.app/Contents/Resources/app.asar/app/main.js:527:16)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:194:7)
[2018-02-05 19:09:37.531] [error] Uncaught Exception: Error: net::ERR_CONNECTION_RESET [raven: 2221c8f207aa41e6ad9424ed5345d3af]
```

**Comment by jwheare** [comment]
Thanks for the report. Were you successfully upgraded to version 0.6.0 when you next launched the app?

**Comment by josve05a** [comment]
@jwheare Nope. Still on Version 0.5.1 (0.5.1.269).

**Comment by josve05a** [comment]
I pressed "Search for update" in the menu now, and this time I got a "Install and Relaunch" button to press, meaning that I was able to download the update this time. Guessing last time was a bad connection on my side?
