### ISSUE TITLE
Dock menu enhancements

### ISSUE THREAD

**Issue by jwheare** [irccloud/irccloud-desktop#49]
macOS: http://electron.atom.io/docs/all/#custom-dock-menu-macos
Windows: http://electron.atom.io/docs/all/#user-tasks-windows
Unity: http://electron.atom.io/docs/all/#unity-launcher-shortcuts-linux

**Comment by robbyoconnor** [comment]
bump

**Comment by robbyoconnor** [comment]
probably related 

Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from /opt/IRCCloud/resources/app.asar/icon.ico
    at TypeError (native)
    at setupTray (/opt/IRCCloud/resources/app.asar/main.js:179:13)
    at EventEmitter.app.toggleTray (/opt/IRCCloud/resources/app.asar/main.js:190:16)
    at file_menu.submenu.push.click (/opt/IRCCloud/resources/app.asar/menu.js:201:17)
    at MenuItem.click (/opt/IRCCloud/resources/electron.asar/browser/api/menu-item.js:81:16)
    at Function.delegate.executeCommand (/opt/IRCCloud/resources/electron.asar/browser/api/menu.js:119:40)

**Comment by jwheare** [comment]
Not related. This issue is to track new features that haven't been developed yet. Your error is being looked into in #61, no need to cross post it to other issues.
