### ISSUE TITLE
Fails to build on Linux

### ISSUE THREAD

**Issue by ricardoamaro** [irccloud/irccloud-desktop#88]
What am i doing wrong?
```
~/repos/irccloud-desktop(master)$ npm install

> electron@1.6.2 postinstall /home/ricardo/repos/irccloud-desktop/node_modules/electron
> node install.js


> irccloud-desktop-build@ postinstall /home/ricardo/repos/irccloud-desktop
> install-app-deps

Using electron-builder.yml configuration file
Installing app dependencies for arch x64 to /home/ricardo/repos/irccloud-desktop/app
irccloud-desktop-build@ /home/ricardo/repos/irccloud-desktop
├─┬ devtron@1.4.0 
│ ├── accessibility-developer-tools@2.12.0 
│ ├── highlight.js@9.10.0 
│ └── humanize-plus@1.8.2 
├─┬ electron@1.6.2 
│ ├─┬ electron-download@3.3.0 
│ │ ├─┬ fs-extra@0.30.0 
│ │ │ ├── graceful-fs@4.1.11 
│ │ │ ├── jsonfile@2.4.0 
│ │ │ ├── klaw@1.3.1 
│ │ │ └── rimraf@2.6.1 
│ │ ├── home-path@1.0.3 
│ │ ├── minimist@1.2.0 
│ │ ├─┬ nugget@2.0.1 
│ │ │ ├─┬ pretty-bytes@1.0.4 
│ │ │ │ ├── get-stdin@4.0.1 
│ │ │ │ └─┬ meow@3.7.0 
│ │ │ │   ├─┬ camelcase-keys@2.1.0 
│ │ │ │   │ └── camelcase@2.1.1 
│ │ │ │   ├─┬ loud-rejection@1.6.0 
│ │ │ │   │ ├─┬ currently-unhandled@0.4.1 
│ │ │ │   │ │ └── array-find-index@1.0.2 
│ │ │ │   │ └── signal-exit@3.0.2 
│ │ │ │   ├── map-obj@1.0.1 
│ │ │ │   ├─┬ redent@1.0.0 
│ │ │ │   │ ├─┬ indent-string@2.1.0 
│ │ │ │   │ │ └─┬ repeating@2.0.1 
│ │ │ │   │ │   └── is-finite@1.0.2 
│ │ │ │   │ └── strip-indent@1.0.1 
│ │ │ │   └── trim-newlines@1.0.0 
│ │ │ ├─┬ progress-stream@1.2.0 
│ │ │ │ ├── speedometer@0.1.4 
│ │ │ │ └─┬ through2@0.2.3 
│ │ │ │   ├─┬ readable-stream@1.1.14 
│ │ │ │   │ └── isarray@0.0.1 
│ │ │ │   └─┬ xtend@2.1.2 
│ │ │ │     └── object-keys@0.4.0 
│ │ │ ├─┬ request@2.81.0 
│ │ │ │ ├── aws-sign2@0.6.0 
│ │ │ │ ├── aws4@1.6.0 
│ │ │ │ ├── caseless@0.12.0 
│ │ │ │ ├─┬ combined-stream@1.0.5 
│ │ │ │ │ └── delayed-stream@1.0.0 
│ │ │ │ ├── extend@3.0.0 
│ │ │ │ ├── forever-agent@0.6.1 
│ │ │ │ ├─┬ form-data@2.1.2 
│ │ │ │ │ └── asynckit@0.4.0 
│ │ │ │ ├─┬ har-validator@4.2.1 
│ │ │ │ │ └── har-schema@1.0.5 
│ │ │ │ ├─┬ hawk@3.1.3 
│ │ │ │ │ ├── boom@2.10.1 
│ │ │ │ │ ├── cryptiles@2.0.5 
│ │ │ │ │ ├── hoek@2.16.3 
│ │ │ │ │ └── sntp@1.0.9 
│ │ │ │ ├─┬ http-signature@1.1.1 
│ │ │ │ │ ├── assert-plus@0.2.0 
│ │ │ │ │ ├─┬ jsprim@1.4.0 
│ │ │ │ │ │ ├── assert-plus@1.0.0 
│ │ │ │ │ │ ├── extsprintf@1.0.2 
│ │ │ │ │ │ ├── json-schema@0.2.3 
│ │ │ │ │ │ └── verror@1.3.6 
│ │ │ │ │ └─┬ sshpk@1.11.0 
│ │ │ │ │   ├── asn1@0.2.3 
│ │ │ │ │   ├── assert-plus@1.0.0 
│ │ │ │ │   ├── bcrypt-pbkdf@1.0.1 
│ │ │ │ │   ├─┬ dashdash@1.14.1 
│ │ │ │ │   │ └── assert-plus@1.0.0 
│ │ │ │ │   ├── ecc-jsbn@0.1.1 
│ │ │ │ │   ├─┬ getpass@0.1.6 
│ │ │ │ │   │ └── assert-plus@1.0.0 
│ │ │ │ │   ├── jodid25519@1.0.2 
│ │ │ │ │   ├── jsbn@0.1.1 
│ │ │ │ │   └── tweetnacl@0.14.5 
│ │ │ │ ├── is-typedarray@1.0.0 
│ │ │ │ ├── isstream@0.1.2 
│ │ │ │ ├── json-stringify-safe@5.0.1 
│ │ │ │ ├─┬ mime-types@2.1.15 
│ │ │ │ │ └── mime-db@1.27.0 
│ │ │ │ ├── oauth-sign@0.8.2 
│ │ │ │ ├── performance-now@0.2.0 
│ │ │ │ ├── qs@6.4.0 
│ │ │ │ ├── safe-buffer@5.0.1 
│ │ │ │ ├── stringstream@0.0.5 
│ │ │ │ ├─┬ tough-cookie@2.3.2 
│ │ │ │ │ └── punycode@1.4.1 
│ │ │ │ ├── tunnel-agent@0.6.0 
│ │ │ │ └── uuid@3.0.1 
│ │ │ ├── single-line-log@1.1.2 
│ │ │ └── throttleit@0.0.2 
│ │ ├─┬ path-exists@2.1.0 
│ │ │ └─┬ pinkie-promise@2.0.1 
│ │ │   └── pinkie@2.0.4 
│ │ ├─┬ rc@1.1.7 
│ │ │ └── deep-extend@0.4.1 
│ │ └─┬ sumchecker@1.3.1 
│ │   └── es6-promise@4.1.0 
│ └─┬ extract-zip@1.6.0 
│   ├─┬ concat-stream@1.5.0 
│   │ └─┬ readable-stream@2.0.6 
│   │   └── isarray@1.0.0 
│   ├── debug@0.7.4 
│   └─┬ yauzl@2.4.1 
│     └─┬ fd-slicer@1.0.1 
│       └── pend@1.2.0 
├─┬ electron-builder@13.11.1 
│ ├─┬ 7zip-bin@2.0.4 
│ │ └── 7zip-bin-linux@1.0.3 
│ ├─┬ asar-electron-builder@0.13.5 
│ │ ├─┬ commander@2.9.0 
│ │ │ └── graceful-readlink@1.0.1 
│ │ └─┬ mkdirp@0.5.1 
│ │   └── minimist@0.0.8 
│ ├─┬ bluebird-lst@1.0.2 
│ │ └── bluebird@3.5.0 
│ ├─┬ chalk@1.1.3 
│ │ ├── ansi-styles@2.2.1 
│ │ ├── escape-string-regexp@1.0.5 
│ │ ├── has-ansi@2.0.0 
│ │ ├── strip-ansi@3.0.1 
│ │ └── supports-color@2.0.0 
│ ├── chromium-pickle-js@0.2.0 
│ ├── cuint@0.2.2 
│ ├── electron-builder-core@13.6.0 
│ ├─┬ electron-builder-http@13.10.1 
│ │ └── debug@2.6.1 
│ ├─┬ electron-builder-util@13.10.1 
│ │ ├── debug@2.6.1 
│ │ ├── ini@1.3.4 
│ │ ├─┬ node-emoji@1.5.1 
│ │ │ └── string.prototype.codepointat@0.2.0 
│ │ ├─┬ source-map-support@0.4.14 
│ │ │ └── source-map@0.5.6 
│ │ ├── stat-mode@0.2.2 
│ │ └── tunnel-agent@0.4.3 
│ ├─┬ electron-download-tf@3.2.0 
│ │ ├── fs-extra@2.1.2 
│ │ ├── path-exists@3.0.0 
│ │ └── sumchecker@2.0.2 
│ ├─┬ electron-macos-sign@1.6.0 
│ │ └── compare-version@0.1.2 
│ ├─┬ electron-publish@13.10.1 
│ │ ├── mime@1.3.4 
│ │ └── progress-ex@2.0.0 
│ ├─┬ fs-extra-p@4.1.0 
│ │ └── fs-extra@2.1.2 
│ ├── hosted-git-info@2.4.1 
│ ├─┬ is-ci@1.0.10 
│ │ └── ci-info@1.0.0 
│ ├── isbinaryfile@3.0.2 
│ ├─┬ js-yaml@3.8.2 
│ │ ├─┬ argparse@1.0.9 
│ │ │ └── sprintf-js@1.0.3 
│ │ └── esprima@3.1.3 
│ ├─┬ minimatch@3.0.3 
│ │ └─┬ brace-expansion@1.1.6 
│ │   ├── balanced-match@0.4.2 
│ │   └── concat-map@0.0.1 
│ ├── node-forge@0.7.1 
│ ├─┬ normalize-package-data@2.3.6 
│ │ ├─┬ is-builtin-module@1.0.0 
│ │ │ └── builtin-modules@1.1.1 
│ │ └─┬ validate-npm-package-license@3.0.1 
│ │   ├─┬ spdx-correct@1.0.2 
│ │   │ └── spdx-license-ids@1.2.2 
│ │   └── spdx-expression-parse@1.0.4 
│ ├─┬ parse-color@1.0.0 
│ │ └── color-convert@0.5.3 
│ ├─┬ plist@2.0.1 
│ │ ├── base64-js@1.1.2 
│ │ ├── xmlbuilder@8.2.2 
│ │ └── xmldom@0.1.27 
│ ├─┬ sanitize-filename@1.6.1 
│ │ └─┬ truncate-utf8-bytes@1.0.2 
│ │   └── utf8-byte-length@1.0.4 
│ ├── semver@5.3.0 
│ ├─┬ update-notifier@2.1.0 
│ │ ├─┬ boxen@1.0.0 
│ │ │ ├── ansi-align@1.1.0 
│ │ │ ├── camelcase@4.0.0 
│ │ │ ├── cli-boxes@1.0.0 
│ │ │ ├─┬ string-width@2.0.0 
│ │ │ │ └── is-fullwidth-code-point@2.0.0 
│ │ │ ├─┬ term-size@0.1.1 
│ │ │ │ └─┬ execa@0.4.0 
│ │ │ │   ├─┬ cross-spawn-async@2.2.5 
│ │ │ │   │ ├─┬ lru-cache@4.0.2 
│ │ │ │   │ │ ├── pseudomap@1.0.2 
│ │ │ │   │ │ └── yallist@2.1.2 
│ │ │ │   │ └─┬ which@1.2.14 
│ │ │ │   │   └── isexe@2.0.0 
│ │ │ │   ├── is-stream@1.1.0 
│ │ │ │   ├── npm-run-path@1.0.0 
│ │ │ │   ├── path-key@1.0.0 
│ │ │ │   └── strip-eof@1.0.0 
│ │ │ └── widest-line@1.0.0 
│ │ ├─┬ configstore@3.0.0 
│ │ │ ├─┬ dot-prop@4.1.1 
│ │ │ │ └── is-obj@1.0.1 
│ │ │ ├─┬ unique-string@1.0.0 
│ │ │ │ └── crypto-random-string@1.0.0 
│ │ │ └─┬ write-file-atomic@1.3.1 
│ │ │   └── slide@1.1.6 
│ │ ├── is-npm@1.0.0 
│ │ ├─┬ latest-version@3.1.0 
│ │ │ └─┬ package-json@4.0.0 
│ │ │   ├─┬ got@6.7.1 
│ │ │   │ ├─┬ create-error-class@3.0.2 
│ │ │   │ │ └── capture-stack-trace@1.0.0 
│ │ │   │ ├── duplexer3@0.1.4 
│ │ │   │ ├── get-stream@3.0.0 
│ │ │   │ ├── is-redirect@1.0.0 
│ │ │   │ ├── is-retry-allowed@1.1.0 
│ │ │   │ ├── lowercase-keys@1.0.0 
│ │ │   │ ├── timed-out@4.0.1 
│ │ │   │ ├── unzip-response@2.0.1 
│ │ │   │ └─┬ url-parse-lax@1.0.0 
│ │ │   │   └── prepend-http@1.0.4 
│ │ │   ├── registry-auth-token@3.1.0 
│ │ │   └── registry-url@3.1.0 
│ │ ├── lazy-req@2.0.0 
│ │ ├── semver-diff@2.1.0 
│ │ └── xdg-basedir@3.0.0 
│ ├─┬ uuid-1345@0.99.6 
│ │ └── macaddress@0.2.8 
│ └─┬ yargs@6.6.0 
│   ├── camelcase@3.0.0 
│   ├─┬ cliui@3.2.0 
│   │ └── wrap-ansi@2.1.0 
│   ├── decamelize@1.2.0 
│   ├── get-caller-file@1.0.2 
│   ├─┬ os-locale@1.4.0 
│   │ └─┬ lcid@1.0.0 
│   │   └── invert-kv@1.0.0 
│   ├─┬ read-pkg-up@1.0.1 
│   │ ├── find-up@1.1.2 
│   │ └─┬ read-pkg@1.1.0 
│   │   ├─┬ load-json-file@1.1.0 
│   │   │ ├─┬ parse-json@2.2.0 
│   │   │ │ └─┬ error-ex@1.3.1 
│   │   │ │   └── is-arrayish@0.2.1 
│   │   │ └─┬ strip-bom@2.0.0 
│   │   │   └── is-utf8@0.2.1 
│   │   └── path-type@1.1.0 
│   ├── require-directory@2.1.1 
│   ├── require-main-filename@1.0.1 
│   ├── set-blocking@2.0.0 
│   ├─┬ string-width@1.0.2 
│   │ ├── code-point-at@1.1.0 
│   │ └─┬ is-fullwidth-code-point@1.0.0 
│   │   └── number-is-nan@1.0.1 
│   ├── which-module@1.0.0 
│   ├── y18n@3.2.1 
│   └─┬ yargs-parser@4.2.1 
│     └── camelcase@3.0.0 
└─┬ eslint@3.18.0 
  ├─┬ babel-code-frame@6.22.0 
  │ └── js-tokens@3.0.1 
  ├─┬ concat-stream@1.6.0 
  │ ├── inherits@2.0.3 
  │ ├─┬ readable-stream@2.2.6 
  │ │ ├── buffer-shims@1.0.0 
  │ │ ├── core-util-is@1.0.2 
  │ │ ├── isarray@1.0.0 
  │ │ ├── process-nextick-args@1.0.7 
  │ │ ├── string_decoder@0.10.31 
  │ │ └── util-deprecate@1.0.2 
  │ └── typedarray@0.0.6 
  ├─┬ debug@2.6.3 
  │ └── ms@0.7.2 
  ├─┬ doctrine@2.0.0 
  │ └── isarray@1.0.0 
  ├─┬ escope@3.6.0 
  │ ├─┬ es6-map@0.1.5 
  │ │ ├── d@1.0.0 
  │ │ ├── es5-ext@0.10.15 
  │ │ ├── es6-iterator@2.0.1 
  │ │ ├── es6-set@0.1.5 
  │ │ ├── es6-symbol@3.1.1 
  │ │ └── event-emitter@0.3.5 
  │ ├── es6-weak-map@2.0.2 
  │ └─┬ esrecurse@4.1.0 
  │   └── estraverse@4.1.1 
  ├─┬ espree@3.4.0 
  │ ├── acorn@4.0.4 
  │ └─┬ acorn-jsx@3.0.1 
  │   └── acorn@3.3.0 
  ├── esquery@1.0.0 
  ├── estraverse@4.2.0 
  ├── esutils@2.0.2 
  ├─┬ file-entry-cache@2.0.0 
  │ ├─┬ flat-cache@1.2.2 
  │ │ ├── circular-json@0.3.1 
  │ │ ├─┬ del@2.2.2 
  │ │ │ ├─┬ globby@5.0.0 
  │ │ │ │ ├─┬ array-union@1.0.2 
  │ │ │ │ │ └── array-uniq@1.0.3 
  │ │ │ │ └── arrify@1.0.1 
  │ │ │ ├── is-path-cwd@1.0.0 
  │ │ │ ├─┬ is-path-in-cwd@1.0.0 
  │ │ │ │ └── is-path-inside@1.0.0 
  │ │ │ └── pify@2.3.0 
  │ │ └─┬ write@0.2.1 
  │ │   └─┬ mkdirp@0.5.1 
  │ │     └── minimist@0.0.8 
  │ └── object-assign@4.1.1 
  ├─┬ glob@7.1.1 
  │ ├── fs.realpath@1.0.0 
  │ ├─┬ inflight@1.0.6 
  │ │ └── wrappy@1.0.2 
  │ ├── once@1.4.0 
  │ └── path-is-absolute@1.0.1 
  ├── globals@9.17.0 
  ├── ignore@3.2.6 
  ├── imurmurhash@0.1.4 
  ├─┬ inquirer@0.12.0 
  │ ├── ansi-escapes@1.4.0 
  │ ├── ansi-regex@2.1.1 
  │ ├─┬ cli-cursor@1.0.2 
  │ │ └─┬ restore-cursor@1.0.1 
  │ │   ├── exit-hook@1.1.1 
  │ │   └── onetime@1.1.0 
  │ ├── cli-width@2.1.0 
  │ ├── figures@1.7.0 
  │ ├─┬ readline2@1.0.1 
  │ │ └── mute-stream@0.0.5 
  │ ├── run-async@0.1.0 
  │ ├── rx-lite@3.1.2 
  │ └── through@2.3.8 
  ├─┬ is-my-json-valid@2.16.0 
  │ ├── generate-function@2.0.0 
  │ ├─┬ generate-object-property@1.2.0 
  │ │ └── is-property@1.0.2 
  │ ├── jsonpointer@4.0.1 
  │ └── xtend@4.0.1 
  ├─┬ is-resolvable@1.0.0 
  │ └── tryit@1.0.3 
  ├─┬ json-stable-stringify@1.0.1 
  │ └── jsonify@0.0.0 
  ├─┬ levn@0.3.0 
  │ ├── prelude-ls@1.1.2 
  │ └── type-check@0.3.2 
  ├── lodash@4.17.4 
  ├─┬ mkdirp@0.5.0 
  │ └── minimist@0.0.8 
  ├── natural-compare@1.4.0 
  ├─┬ optionator@0.8.2 
  │ ├── deep-is@0.1.3 
  │ ├── fast-levenshtein@2.0.6 
  │ └── wordwrap@1.0.0 
  ├── path-is-inside@1.0.2 
  ├── pluralize@1.2.1 
  ├── progress@1.1.8 
  ├─┬ require-uncached@1.0.3 
  │ ├─┬ caller-path@0.1.0 
  │ │ └── callsites@0.2.0 
  │ └── resolve-from@1.0.1 
  ├─┬ shelljs@0.7.7 
  │ ├── interpret@1.0.1 
  │ └─┬ rechoir@0.6.2 
  │   └─┬ resolve@1.3.2 
  │     └── path-parse@1.0.5 
  ├── strip-bom@3.0.0 
  ├── strip-json-comments@2.0.1 
  ├─┬ table@3.8.3 
  │ ├─┬ ajv@4.11.5 
  │ │ └── co@4.6.0 
  │ ├── ajv-keywords@1.5.1 
  │ ├── slice-ansi@0.0.4 
  │ └─┬ string-width@2.0.0 
  │   └── is-fullwidth-code-point@2.0.0 
  ├── text-table@0.2.0 
  └─┬ user-home@2.0.0 
    └── os-homedir@1.0.2 

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-mac@^1.0.1 (node_modules/7zip-bin/node_modules/7zip-bin-mac):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-mac@1.0.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-win@^2.0.2 (node_modules/7zip-bin/node_modules/7zip-bin-win):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-win@2.0.2: wanted {"os":"win32","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN irccloud-desktop-build@ No repository field.
npm WARN irccloud-desktop-build@ No license field.
ricardo@ricardo-T440s:~/repos/irccloud-desktop(master)$ make dist
npm run dist

> irccloud-desktop-build@ dist /home/ricardo/repos/irccloud-desktop
> build

Using electron-builder.yml configuration file
Rebuilding native production dependencies for linux:x64
Packaging for linux x64 using electron 1.6.2 to dist/linux-unpacked
Unhandled rejection Error: Exit code: ENOENT. spawn icns2png ENOENT
    at /home/ricardo/repos/irccloud-desktop/node_modules/electron-builder-util/src/util.ts:75:16
    at exithandler (child_process.js:220:5)
    at ChildProcess.errorhandler (child_process.js:232:5)
    at emitOne (events.js:77:13)
    at ChildProcess.emit (events.js:169:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickCallback (node.js:355:17)
From previous event:
    at exec (/home/ricardo/repos/irccloud-desktop/node_modules/electron-builder-util/src/util.ts:53:3)
    at /home/ricardo/repos/irccloud-desktop/node_modules/electron-builder/src/targets/LinuxTargetHelper.ts:167:28
    at next (native)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at LinuxTargetHelper.createFromIcns (/home/ricardo/repos/irccloud-desktop/node_modules/electron-builder/out/targets/LinuxTargetHelper.js:216:11)
    at /home/ricardo/repos/irccloud-desktop/node_modules/electron-builder/src/targets/LinuxTargetHelper.ts:54:25
From previous event:
    at LinuxTargetHelper.computeDesktopIcons (/home/ricardo/repos/irccloud-desktop/node_modules/electron-builder/out/targets/LinuxTargetHelper.js:84:11)
    at new LinuxTargetHelper (/home/ricardo/repos/irccloud-desktop/node_modules/electron-builder/src/targets/LinuxTargetHelper.ts:17:23)
    at getHelper (/home/ricardo/repos/irccloud-desktop/node_modules/electron-builder/src/linuxPackager.ts:32:18)
    at /home/ricardo/repos/irccloud-desktop/node_modules/electron-builder/src/linuxPackager.ts:61:122
    at mapper (/home/ricardo/repos/irccloud-desktop/node_modules/electron-builder/src/targets/targetFactory.ts:15:16)
    at LinuxPackager.createTargets (/home/ricardo/repos/irccloud-desktop/node_modules/electron-builder/src/linuxPackager.ts:61:7)
    at createTargets (/home/ricardo/repos/irccloud-desktop/node_modules/electron-builder/src/targets/targetFactory.ts:22:12)
    at /home/ricardo/repos/irccloud-desktop/node_modules/electron-builder/src/packager.ts:231:41
From previous event:
    at Packager.doBuild (/home/ricardo/repos/irccloud-desktop/node_modules/electron-builder/out/packager.js:351:11)
    at /home/ricardo/repos/irccloud-desktop/node_modules/electron-builder/src/packager.ts:159:38
    at next (native)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Packager.build (/home/ricardo/repos/irccloud-desktop/node_modules/electron-builder/out/packager.js:257:11)
    at /home/ricardo/repos/irccloud-desktop/node_modules/electron-builder/src/builder.ts:217:33
    at next (native)
From previous event:
    at build (/home/ricardo/repos/irccloud-desktop/node_modules/electron-builder/out/builder.js:70:21)
    at Object.<anonymous> (/home/ricardo/repos/irccloud-desktop/node_modules/electron-builder/out/cli/build-cli.js:71:41)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

Building AppImage for arch x64
Error: Exit code: ENOENT. spawn icns2png ENOENT
    at /home/ricardo/repos/irccloud-desktop/node_modules/electron-builder-util/src/util.ts:75:16
    at exithandler (child_process.js:220:5)
    at ChildProcess.errorhandler (child_process.js:232:5)
    at emitOne (events.js:77:13)
    at ChildProcess.emit (events.js:169:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickCallback (node.js:355:17)
From previous event:
    at exec (/home/ricardo/repos/irccloud-desktop/node_modules/electron-builder-util/src/util.ts:53:3)
    at /home/ricardo/repos/irccloud-desktop/node_modules/electron-builder/src/targets/LinuxTargetHelper.ts:167:28
    at next (native)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at LinuxTargetHelper.createFromIcns (/home/ricardo/repos/irccloud-desktop/node_modules/electron-builder/out/targets/LinuxTargetHelper.js:216:11)
    at /home/ricardo/repos/irccloud-desktop/node_modules/electron-builder/src/targets/LinuxTargetHelper.ts:54:25
From previous event:
    at LinuxTargetHelper.computeDesktopIcons (/home/ricardo/repos/irccloud-desktop/node_modules/electron-builder/out/targets/LinuxTargetHelper.js:84:11)
    at new LinuxTargetHelper (/home/ricardo/repos/irccloud-desktop/node_modules/electron-builder/src/targets/LinuxTargetHelper.ts:17:23)
    at getHelper (/home/ricardo/repos/irccloud-desktop/node_modules/electron-builder/src/linuxPackager.ts:32:18)
    at /home/ricardo/repos/irccloud-desktop/node_modules/electron-builder/src/linuxPackager.ts:61:122
    at mapper (/home/ricardo/repos/irccloud-desktop/node_modules/electron-builder/src/targets/targetFactory.ts:15:16)
    at LinuxPackager.createTargets (/home/ricardo/repos/irccloud-desktop/node_modules/electron-builder/src/linuxPackager.ts:61:7)
    at createTargets (/home/ricardo/repos/irccloud-desktop/node_modules/electron-builder/src/targets/targetFactory.ts:22:12)
    at /home/ricardo/repos/irccloud-desktop/node_modules/electron-builder/src/packager.ts:231:41
From previous event:
    at Packager.doBuild (/home/ricardo/repos/irccloud-desktop/node_modules/electron-builder/out/packager.js:351:11)
    at /home/ricardo/repos/irccloud-desktop/node_modules/electron-builder/src/packager.ts:159:38
    at next (native)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Packager.build (/home/ricardo/repos/irccloud-desktop/node_modules/electron-builder/out/packager.js:257:11)
    at /home/ricardo/repos/irccloud-desktop/node_modules/electron-builder/src/builder.ts:217:33
    at next (native)
From previous event:
    at build (/home/ricardo/repos/irccloud-desktop/node_modules/electron-builder/out/builder.js:70:21)
    at Object.<anonymous> (/home/ricardo/repos/irccloud-desktop/node_modules/electron-builder/out/cli/build-cli.js:71:41)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

npm ERR! Linux 4.4.0-63-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/local/bin/npm" "run" "dist"
npm ERR! node v4.2.6
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! irccloud-desktop-build@ dist: `build`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the irccloud-desktop-build@ dist script 'build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the irccloud-desktop-build package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs irccloud-desktop-build
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls irccloud-desktop-build
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ricardo/repos/irccloud-desktop/npm-debug.log
Makefile:2: recipe for target 'dist' failed
make: *** [dist] Error 1
```

**Comment by russss** [comment]
You're missing some build dependencies, which admittedly aren't hugely well documented. On Debian-ish distros you want:

   apt-get install icnsutils graphicsmagick xz-utils

**Comment by ricardoamaro** [comment]
Ok, thank you @russss
maybe we should add that to the compile instructions
