### ISSUE TITLE
Build fails on Zesty Zapus

### ISSUE THREAD

**Issue by ChrisMacNaughton** [irccloud/irccloud-desktop#90]
```
$ make dist
npm run dist
> irccloud-desktop-build@ dist /mnt/media/projects/irccloud-desktop
> build
Using electron-builder.yml configuration file
Rebuilding native production dependencies for linux:x64
Packaging for linux x64 using electron 1.6.5 to dist/linux-unpacked
Building AppImage for arch x64
Error: Exit code: 127. Command failed: /home/chris/.cache/electron-builder/AppImage/AppImage-09-07-16-linux/xorriso -joliet on -volid AppImage -dev /mnt/media/projects/irccloud-desktop/dist/irccloud-desktop-0.4.0-x86_64.AppImage -padding 0
-map /mnt/media/projects/irccloud-desktop/dist/linux-unpacked /usr/bin -map /mnt/media/projects/irccloud-desktop/node_modules/electron-builder/templates/linux/AppRun.sh /AppRun -map /tmp/electron-builder-3c17-15b9effa430-0/0-3-IRCCloud.desk
top /irccloud-desktop.desktop -map /tmp/electron-builder-3c17-15b9effa430-0/0-2-linux.iconset/icon_16x16x32.png /usr/share/icons/default/16x16/apps/irccloud-desktop.png -map /tmp/electron-builder-3c17-15b9effa430-0/0-2-linux.iconset/icon_24
x24x32.png /usr/share/icons/default/24x24/apps/irccloud-desktop.png -map /tmp/electron-builder-3c17-15b9effa430-0/0-2-linux.iconset/icon_32x32x32.png /usr/share/icons/default/32x32/apps/irccloud-desktop.png -map /tmp/electron-builder-3c17-1
5b9effa430-0/0-2-linux.iconset/icon_48x48x32.png /usr/share/icons/default/48x48/apps/irccloud-desktop.png -map /tmp/electron-builder-3c17-15b9effa430-0/0-2-linux.iconset/icon_64x64x32.png /usr/share/icons/default/64x64/apps/irccloud-desktop
.png -map /tmp/electron-builder-3c17-15b9effa430-0/0-2-linux.iconset/icon_96x96x32.png /usr/share/icons/default/96x96/apps/irccloud-desktop.png -map /tmp/electron-builder-3c17-15b9effa430-0/0-2-linux.iconset/icon_128x128x32.png /usr/share/i
cons/default/128x128/apps/irccloud-desktop.png -map /tmp/electron-builder-3c17-15b9effa430-0/0-2-linux.iconset/icon_256x256x32.png /usr/share/icons/default/256x256/apps/irccloud-desktop.png -map /tmp/electron-builder-3c17-15b9effa430-0/0-2-
linux.iconset/icon_512x512x32.png /usr/share/icons/default/512x512/apps/irccloud-desktop.png -map /tmp/electron-builder-3c17-15b9effa430-0/0-2-linux.iconset/icon_256x256x32.png /.DirIcon -chown_r 0 / -- -zisofs level=9:block_size=128k:by_ma
gic=off set_filter_r --zisofs /
/home/chris/.cache/electron-builder/AppImage/AppImage-09-07-16-linux/xorriso: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory
/home/chris/.cache/electron-builder/AppImage/AppImage-09-07-16-linux/xorriso: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory
    at /mnt/media/projects/irccloud-desktop/node_modules/electron-builder-util/src/util.ts:75:16
    at ChildProcess.exithandler (child_process.js:220:5)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:854:16)
    at Socket.<anonymous> (internal/child_process.js:330:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:487:12)
From previous event:
    at exec (/mnt/media/projects/irccloud-desktop/node_modules/electron-builder-util/src/util.ts:53:3)
    at /mnt/media/projects/irccloud-desktop/node_modules/electron-builder/src/targets/appImage.ts:79:5
    at next (native)
From previous event:
    at AppImageTarget.build (/mnt/media/projects/irccloud-desktop/node_modules/electron-builder/out/targets/appImage.js:144:11)
    at /mnt/media/projects/irccloud-desktop/node_modules/electron-builder/src/platformPackager.ts:103:85
From previous event:
    at LinuxPackager.packageInDistributableFormat (/mnt/media/projects/irccloud-desktop/node_modules/electron-builder/src/platformPackager.ts:103:41)
    at /mnt/media/projects/irccloud-desktop/node_modules/electron-builder/src/platformPackager.ts:99:10
From previous event:
    at LinuxPackager.pack (/mnt/media/projects/irccloud-desktop/node_modules/electron-builder/out/platformPackager.js:160:11)
    at /mnt/media/projects/irccloud-desktop/node_modules/electron-builder/src/packager.ts:231:22
From previous event:
    at Packager.doBuild (/mnt/media/projects/irccloud-desktop/node_modules/electron-builder/out/packager.js:351:11)
    at /mnt/media/projects/irccloud-desktop/node_modules/electron-builder/src/packager.ts:159:38
    at next (native)
    at processImmediate [as _immediateCallback] (timers.js:396:17)
From previous event:
    at Packager.build (/mnt/media/projects/irccloud-desktop/node_modules/electron-builder/out/packager.js:257:11)
    at /mnt/media/projects/irccloud-desktop/node_modules/electron-builder/src/builder.ts:217:33
    at next (native)
From previous event:
    at build (/mnt/media/projects/irccloud-desktop/node_modules/electron-builder/out/builder.js:70:21)
    at Object.<anonymous> (/mnt/media/projects/irccloud-desktop/node_modules/electron-builder/out/cli/build-cli.js:71:41)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:990:3
npm ERR! Linux 4.10.0-19-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "dist"
npm ERR! node v4.7.2
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! irccloud-desktop-build@ dist: `build`
npm ERR! Exit status 255
npm ERR!
npm ERR! Failed at the irccloud-desktop-build@ dist script 'build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the irccloud-desktop-build package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs irccloud-desktop-build
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls irccloud-desktop-build
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/media/projects/irccloud-desktop/npm-debug.log
Makefile:2: recipe for target 'dist' failed
make: *** [dist] Error 1
```

Looks like it's a problem with readline, but I have:
```
$ dpkg -l|grep readline
ii  libreadline-dev:amd64                        7.0-0ubuntu2                                    amd64        GNU readline and history libraries, development files
```

referenced npm-debug.log is at: http://termbin.com/769q

**Comment by russss** [comment]
This is electron-userland/electron-builder#993 and there are some workarounds in that issue.

It's a bug on electron-builder's end but I'll leave this issue open until that's fixed.

**Comment by jwheare** [comment]
@ChrisMacNaughton we updated electron-builder and that fix should be in now. Closing this issue but let us know if it's still happening.
